import { Section, Container } from "@/components/craft";
import Link from "next/link";
import { LuArrowLeftCircle, LuArrowRightCircle } from "react-icons/lu";

const page = () => {
  return (
    <Section className="not-prose">
      <Container>
        <div className="w-full h-full m-auto max-w-5xl md:py-10 py-4 lg:pl-32 md:pl-20 pl-8 flex flex-col gap-6">
          <h1 className="text-3xl md:text-6xl font-semibold tracking-tight">
            Use Cases of $GEPS Token 
          </h1>
          <div className="md:text-lg">
            <div className="md:block">
                <span className="font-semibold text-xl">GEPS tokens are designed with multifaceted use cases within the GEPS ecosystem. They serve as the key to participating in a range of activities, including but not limited to:</span><br/><br/>
                <span className="font-semibold text-xl">Decentralized Trading</span><br/>
                <ul className="marker:text-green-600 list-disc ps-5 space-y-2 dark:text-white">
                    <li>Users can engage in peer-to-peer trading on the GEPS exchange platform, enjoying lower fees and improved security.</li>
                </ul>
                <br/>
                <span className="font-semibold text-xl">Asset Management</span><br/>
                <ul className="marker:text-green-600 list-disc ps-5 space-y-2 dark:text-white">
                    <li>GEPS tokens unlock the potential for innovative asset management tools, i.e., Purchase of GEPS standalone power stations, Buy/Sell electricity units, Order Installation & maintenance services, all this can be achieved from anywhere anytime online without any physical presence catering to people around the world.</li>
                </ul>
                <br/>
                <span className="font-semibold text-xl">Staking</span><br/>
                <ul className="marker:text-green-600 list-disc ps-5 space-y-2 dark:text-white">
                    <li>Through staking and participation in liquidity pools, GEPS holders can Fund Projects and actually own GEPS Power generation units, Entire power generated by such power stations, can be sold on our online platform and entire revenue earned directly goes to the owner of such units incentivizing long-term engagement and contributing to ecosystem liquidity.</li>
                </ul>
            </div>
            <p className="text-sm mt-5 flex flex-row gap-6">
            <Link
                href="/whitepaper/geps"
                className="flex items-center justify-center gap-x-1 py-3 px-4 text-white font-medium transform-gpu dark:[border:1px_solid_rgba(255,255,255,.1)] dark:[box-shadow:0_-20px_80px_-20px_#8686f01f_inset] rounded-full md:inline-flex "
              >
                <LuArrowLeftCircle/>
                Previous: What is $GEPS
              </Link>
              <Link
                href="/whitepaper/special"
                className="flex items-center justify-center gap-x-1 py-3 px-4 text-white font-medium transform-gpu dark:[border:1px_solid_rgba(255,255,255,.1)] dark:[box-shadow:0_-20px_80px_-20px_#8686f01f_inset] rounded-full md:inline-flex "
              >
                Next: What’s so special about $GEPS 
                <LuArrowRightCircle/>
              </Link>
            </p>
          </div>
        </div>
      </Container>
    </Section>
  );
};

export default page;