import * as Craft from "@/components/craft";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

import React from "react";

type FAQItem = {
  question: string;
  answer: string;
  link?: string;
};

const content: FAQItem[] = [
  {
    question: "What is a presale?",
    answer:
      "A presale offers a limited number of tokens at a discounted price to early participants. It allows you to be part of a project before its public launch, similar to an exclusive club. Pre-sales provide an opportunity to buy tokens before they hit exchanges.",
  },
  {
    question: "What is GEPS?",
    answer:
      "GEPS is a ground-breaking platform where you can own fractional shares of Green Energy Power Stations using $GEPS tokens. You can also purchase electricity generated by these stations. Each GEPS token represents real-world assets (land and equipment) and allows investments starting from $10. Owners receive monthly income and can trade shares on the GEPS marketplace.",
  },
  {
    question: "Why participate in the presale?",
    answer:
      "The GEPS presale lets you join a passionate community that believes in clean energy and sustainability. By getting in early, you benefit from potential token discounts and contribute to the project’s success. Presale funds accelerate implementation while ensuring a smooth launch.",
  },
  {
    question: "What is the $GEPS token?",
    answer:
      "$GEPS tokens grant access to GEPS features:\n"+
      "Voting rights for project decisions.\n"+
      "Purchasing Green Energy Power Stations and trading electricity.\n"+
      "Monthly income from GEPS operations, with potential token appreciation.\n",
  },
  {
    question: "Are my tokens safe?",
    answer: "GEPS prioritizes security, using industry-standard measures and complete transparency. Our 24/7 security team ensures asset safety. While all investments carry risk, participating in the presale reflects our commitment to secure fractional ownership in the power sector.",

  },
  {
    question: "Is there a vesting period for tokens?",
    answer: "No vesting period for presale investors."
  },
  {
    question: "Where do I find my purchased tokens?",
    answer: "Click the “Connect Wallet” button in the top right corner, then select “Go to Dashboard.” Token distribution begins 48 hours after the presale ends."
  },
  {
    question: "What’s the launch price for $GEPS?",
    answer: "The initial listing price for 1 $GEPS is $0.50 during launch."
  },
  {
    question: "When is the $GEPS launch?",
    answer: "The $GEPS launch date occurs 48 hours after the presale concludes."
  }
];

const FAQs = () => {
    return (
      <Craft.Section id="faqs">
        <Craft.Container>
          <h3 className="!-mt-8 font-bold text-4xl mb-2">Frequently Asked Questions</h3>
          <h4 className="text-muted-foreground font-medium text-xl">
            Can&apos;t find the answer you&apos;re looking for? Reach out to our
            customer support team.
          </h4>
          <div className="mt-2 md:mt-5 not-prose flex flex-col gap-4">
            {content.map((item, index) => (
              <Accordion key={index} type="single" collapsible>
                <AccordionItem
                  value={item.question}
                  className="hover:bg-green-900/25 transition-all border px-4 bg-muted/20 rounded-md text-[18px]"
                >
                  <AccordionTrigger className="text-left hover:underline">
                    {item.question}
                  </AccordionTrigger>
                  <AccordionContent className="text-base md:w-auto">
                    {item.answer}
                  </AccordionContent>
                </AccordionItem>
              </Accordion>
            ))}
          </div>
        </Craft.Container>
      </Craft.Section>
    );
  };
  
  export default FAQs;